-- Создание пользователя в основной базе
BEGIN
  EXECUTE IMMEDIATE 'CREATE USER aviasales IDENTIFIED BY aviasales';
  EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SESSION, CREATE TABLE TO aviasales';
  EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO aviasales';
  DBMS_OUTPUT.PUT_LINE('User AVIASALES created in CDB$ROOT.');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -01920 THEN -- user already exists
      DBMS_OUTPUT.PUT_LINE('User AVIASALES already exists in CDB$ROOT.');
    ELSE
      RAISE;
    END IF;
END;
/

-- Создание пользователя в XEPDB1
ALTER SESSION SET CONTAINER = XEPDB1;

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER aviasales IDENTIFIED BY aviasales';
  EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SESSION, CREATE TABLE TO aviasales';
  EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO aviasales';
  DBMS_OUTPUT.PUT_LINE('User AVIASALES created in XEPDB1.');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -01920 THEN -- user already exists
      DBMS_OUTPUT.PUT_LINE('User AVIASALES already exists in XEPDB1.');
    ELSE
      RAISE;
    END IF;
END;
/